### ISSUE TITLE
Access to Docker Container /bin/bash

### ISSUE THREAD

**Issue by jasonbillebault** [traggo/server#133]
**Have you read the documentation?**
- [ x ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up traggo in**
- [ x ] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

I'm not familiar with Docker and it's a great opportunity to learn it by installing your application on a docker. 

I ran a docker container but I want to control Backup and Restoration of config changes. I would like to know how to access to the content in SSH in order to understand the content ?
 
I saw a lot of Google answers about running this command :  

`docker exec -it *id* /bin/bash `
without success, i tried also /bin/sh

Is that impossible for your container or is there something I miss ?

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, browser requests, etc.

**Comment by jmattheis** [comment]
The docker image uses `scatch` as base image, so only the traggo binary is available there
https://github.com/traggo/server/blob/017af77e2940d97c2b921f13f8847979d00bbb94/docker/Dockerfile#L1-L5

**Comment by TheBlusky** [comment]
Even if you can see some website recommending it,  you (usually) should not use `docker exec bash`.

Docker containers are ephemeral. In your case, you want to retrieve files in order to perform backup. Instead on doing backup within Traggo container, you should retrieve your files using the volume volume (`-v` if using docker in CLI, or the `volumes` section in your docker-compose.yml file). They should be readable from your host, and (if needed) from another container if configured with a shared volume.

**Comment by c-nv-s** [comment]
are there any new releases planned for traggo soon? just curious.

**Comment by jmattheis** [comment]
@c-nv-s depends if there is something that can be released.
